# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake3

# The command to remove a file.
RM = /usr/bin/cmake3 -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sali200/cs225git/ai10-sali200-drugutt2-priyak5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sali200/cs225git/ai10-sali200-drugutt2-priyak5

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake3 --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sali200/cs225git/ai10-sali200-drugutt2-priyak5/CMakeFiles /home/sali200/cs225git/ai10-sali200-drugutt2-priyak5/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sali200/cs225git/ai10-sali200-drugutt2-priyak5/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test-parsing

# Build rule for target.
test-parsing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-parsing
.PHONY : test-parsing

# fast build rule for target.
test-parsing/fast:
	$(MAKE) $(MAKESILENT) -f parsing/CMakeFiles/test-parsing.dir/build.make parsing/CMakeFiles/test-parsing.dir/build
.PHONY : test-parsing/fast

#=============================================================================
# Target rules for targets named main-parsing

# Build rule for target.
main-parsing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main-parsing
.PHONY : main-parsing

# fast build rule for target.
main-parsing/fast:
	$(MAKE) $(MAKESILENT) -f parsing/CMakeFiles/main-parsing.dir/build.make parsing/CMakeFiles/main-parsing.dir/build
.PHONY : main-parsing/fast

#=============================================================================
# Target rules for targets named ParsingLib

# Build rule for target.
ParsingLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ParsingLib
.PHONY : ParsingLib

# fast build rule for target.
ParsingLib/fast:
	$(MAKE) $(MAKESILENT) -f parsing/CMakeFiles/ParsingLib.dir/build.make parsing/CMakeFiles/ParsingLib.dir/build
.PHONY : ParsingLib/fast

#=============================================================================
# Target rules for targets named main-parse-dijkstra

# Build rule for target.
main-parse-dijkstra: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main-parse-dijkstra
.PHONY : main-parse-dijkstra

# fast build rule for target.
main-parse-dijkstra/fast:
	$(MAKE) $(MAKESILENT) -f parse-dijkstra/CMakeFiles/main-parse-dijkstra.dir/build.make parse-dijkstra/CMakeFiles/main-parse-dijkstra.dir/build
.PHONY : main-parse-dijkstra/fast

#=============================================================================
# Target rules for targets named test-parse-dijkstra

# Build rule for target.
test-parse-dijkstra: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-parse-dijkstra
.PHONY : test-parse-dijkstra

# fast build rule for target.
test-parse-dijkstra/fast:
	$(MAKE) $(MAKESILENT) -f parse-dijkstra/CMakeFiles/test-parse-dijkstra.dir/build.make parse-dijkstra/CMakeFiles/test-parse-dijkstra.dir/build
.PHONY : test-parse-dijkstra/fast

#=============================================================================
# Target rules for targets named Parse-DijkstraLib

# Build rule for target.
Parse-DijkstraLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Parse-DijkstraLib
.PHONY : Parse-DijkstraLib

# fast build rule for target.
Parse-DijkstraLib/fast:
	$(MAKE) $(MAKESILENT) -f parse-dijkstra/CMakeFiles/Parse-DijkstraLib.dir/build.make parse-dijkstra/CMakeFiles/Parse-DijkstraLib.dir/build
.PHONY : Parse-DijkstraLib/fast

#=============================================================================
# Target rules for targets named test-visual-dfs

# Build rule for target.
test-visual-dfs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-visual-dfs
.PHONY : test-visual-dfs

# fast build rule for target.
test-visual-dfs/fast:
	$(MAKE) $(MAKESILENT) -f visual-dfs/CMakeFiles/test-visual-dfs.dir/build.make visual-dfs/CMakeFiles/test-visual-dfs.dir/build
.PHONY : test-visual-dfs/fast

#=============================================================================
# Target rules for targets named main-visual-dfs

# Build rule for target.
main-visual-dfs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main-visual-dfs
.PHONY : main-visual-dfs

# fast build rule for target.
main-visual-dfs/fast:
	$(MAKE) $(MAKESILENT) -f visual-dfs/CMakeFiles/main-visual-dfs.dir/build.make visual-dfs/CMakeFiles/main-visual-dfs.dir/build
.PHONY : main-visual-dfs/fast

#=============================================================================
# Target rules for targets named Visual-DFSLib

# Build rule for target.
Visual-DFSLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Visual-DFSLib
.PHONY : Visual-DFSLib

# fast build rule for target.
Visual-DFSLib/fast:
	$(MAKE) $(MAKESILENT) -f visual-dfs/CMakeFiles/Visual-DFSLib.dir/build.make visual-dfs/CMakeFiles/Visual-DFSLib.dir/build
.PHONY : Visual-DFSLib/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/main.dir/build.make src/CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named MainLib

# Build rule for target.
MainLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MainLib
.PHONY : MainLib

# fast build rule for target.
MainLib/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/MainLib.dir/build.make src/CMakeFiles/MainLib.dir/build
.PHONY : MainLib/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MainLib"
	@echo "... Parse-DijkstraLib"
	@echo "... ParsingLib"
	@echo "... Visual-DFSLib"
	@echo "... main"
	@echo "... main-parse-dijkstra"
	@echo "... main-parsing"
	@echo "... main-visual-dfs"
	@echo "... test-parse-dijkstra"
	@echo "... test-parsing"
	@echo "... test-visual-dfs"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

